language: ruby
services:
  - redis-server
rvm:
  - 1.9.3
  - jruby
  - 2.0.0
before_script:
  - cp -f config/database_jenkins.yml config/database.yml
  - cp -f db/words.sample.csv db/words.csv
  - RAILS_ENV=test bundle exec rake log:clear db:drop db:create db:migrate
script: bundle exec rspec spec
env:
  - MXIT_CLIENT_ID=1 SHINKA_AUID=1 GA_TRACKING_CODE=1