production:
  adapter: postgresql
  database: hangman_league
  username: <%= ENV['DOTCLOUD_DATA_SQL_LOGIN'] %>
  password: <%= ENV['DOTCLOUD_DATA_SQL_PASSWORD'] %>
  port: <%= ENV['DOTCLOUD_DATA_SQL_PORT'] %>
  host: <%= ENV['DOTCLOUD_DATA_SQL_HOST'] %>
  pool: 5
  timeout: 5000

