production:
  adapter: postgresql
  database: hangman_league
  username: <%= ENV['DOTCLOUD_DB_SQL_LOGIN'] %>
  password: <%= ENV['DOTCLOUD_DB_SQL_PASSWORD'] %>
  port: <%= ENV['DOTCLOUD_DB_SSH_PORT'] %>
  host: <%= ENV['DOTCLOUD_DB_SSH_HOST'] %>
  pool: 5
