<% env = JSON.parse(File.read('/home/dotcloud/environment.json')) %>
production:
  adapter: postgresql
  database: hangman_league
  username: <%= env['DOTCLOUD_DATA_SQL_LOGIN'] %>
  password: <%= env['DOTCLOUD_DATA_SQL_PASSWORD'] %>
  port: <%= env['DOTCLOUD_DATA_SQL_PORT'] %>
  host: <%= env['DOTCLOUD_DATA_SQL_HOST'] %>
  pool: 5
  timeout: 5000

