jobs:
  winner.create_daily_winners:
    job: App::Jobs::CreateDailyWinners
    cron: '0 50 23 * * ?'
    description: Select the Daily Winners
  user.new_day_set_scores:
      job: App::Jobs::NewDaySetScores
      cron: '0 1 0 * * ?'
      description: Set players scores to zero
  user.add_clue_point_to_active_players:
    job: App::Jobs::AddCluePointsToActivePlayers
    cron: '0 55 23 * * ?'
    description: Give players there clue points for playing
  winner.create_weekly_winners:
    job: App::Jobs::CreateWeeklyWinners
    cron: '0 45 23 ? * SUN'
    description: Select the Weekly Winners on sunday evening
  redeem_winning.issue_mxit_money_to_users:
    job: App::Jobs::IssueMxitMoneyToUsers
    cron: '0 0,30 * * * ?'
    description: Payout Mxit Money
  airtime_voucher.issue_airtime_to_users:
      job: App::Jobs::IssueAirtimeToUsers
      cron: '0 15,45 * * * ?'
      description: Payout Mxit Money
  stats.record_hourly_stats:
    job: App::Jobs::RecordHourlyStats
    cron: '0 0 * * * ?'
    description: Record hourly stats
